// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package subtract

// Exports represents the caller-defined exports from "docs:subtractor/subtract@0.1.0".
var Exports struct {
	// Subtract represents the caller-defined, exported function "subtract".
	//
	//	subtract: func(a: s32, b: s32) -> s32
	Subtract func(a int32, b int32) (result int32)
}
