// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package subtract represents the exported interface "docs:subtractor/subtract@0.1.0".
package subtract

//go:wasmexport docs:subtractor/subtract@0.1.0#subtract
//export docs:subtractor/subtract@0.1.0#subtract
func wasmexport_Subtract(a0 uint32, b0 uint32) (result0 uint32) {
	a := (int32)((uint32)(a0))
	b := (int32)((uint32)(b0))
	result := Exports.Subtract(a, b)
	result0 = (uint32)(result)
	return
}
