// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package add

// Exports represents the caller-defined exports from "docs:adder/add@0.1.0".
var Exports struct {
	// Add represents the caller-defined, exported function "add".
	//
	//	add: func(a: u32, b: u32) -> u32
	Add func(a uint32, b uint32) (result uint32)
}
