// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package add represents the exported interface "docs:adder/add@0.1.0".
package add

//go:wasmexport docs:adder/add@0.1.0#add
//export docs:adder/add@0.1.0#add
func wasmexport_Add(a0 uint32, b0 uint32) (result0 uint32) {
	a := (int32)((uint32)(a0))
	b := (int32)((uint32)(b0))
	result := Exports.Add(a, b)
	result0 = (uint32)(result)
	return
}
